### ISSUE TITLE
"void * user_data" param of Python layer "io_uring_prep_cancel"

### ISSUE THREAD

**Issue by openalmeida** [YoSTEALTH/Liburing#11]
Hi,

an additional CFFI transfer is required to suit for the clang layer `void *user_data` define ?

```python
# python
liburing.io_uring_prep_cancel(sqe, ???, 0)  # to cancel a socket ACCEPT sqe
                                            # e.g sqe.user_data = 1, how to transfer it to type "void *" 
```

```c
// clang
static inline void io_uring_prep_cancel(struct io_uring_sqe *sqe, void *user_data, int flags);
```

**Comment by openalmeida** [comment]
got it from the ffi cast api
```python
liburing.io_uring_prep_cancel(sqe, liburing.helper.cast("void *", user_data), 0)
```

**Comment by YoSTEALTH** [comment]
@openalmeida thanks for point this out. `user_data` is used in few different places and it should be `__u64` not sure why they are using `void *` in few functions

**Comment by YoSTEALTH** [comment]
@openalmeida Have you tried
```python
liburing.io_uring_prep_cancel(sqe, user_data, 0)
```
I think this should work as well!

**Comment by openalmeida** [comment]
> @openalmeida Have you tried
> 
> ```python
> liburing.io_uring_prep_cancel(sqe, user_data, 0)
> ```
> 
> I think this should work as well! As long as `user_data` type is `int`

>>> It will case cffi "void int *" dismatch error:
>>> ```TypeError: initializer for ctype 'void *' must be a cdata pointer, not int```
>>> the way of working for me is below which commented 8 days ago.

> got it from the ffi cast api
> 
> ```python
> liburing.io_uring_prep_cancel(sqe, liburing.helper.cast("void *", user_data), 0)
> ```

**Comment by YoSTEALTH** [comment]
@openalmeida I ended up creating wrapper functions to help with proper type used for `user_data` https://github.com/YoSTEALTH/Liburing/commit/17ae3317a74a31a389a20bfd68f3a588e9cab19a adapt your code accordingly
