### ISSUE TITLE
Initialization fails on kernel 5.10

### ISSUE THREAD

**Issue by danielmitterdorfer** [YoSTEALTH/Liburing#12]
### Environment info

* Kernel version: `5.10.16-051016-generic`
* glibc version: `ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31`
* Python version: 3.8.5 (CPython)
* Library version: master (i.e. https://github.com/YoSTEALTH/Liburing/commit/17ae3317a74a31a389a20bfd68f3a588e9cab19a)

#### Actual behavior

When attempting to issue `import liburing` (e.g. in an interactive Python session) I get:

```
>>> import liburing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dm/liburing-test/.venv/lib/python3.8/site-packages/liburing/__init__.py", line 17, in <module>
    del lib.STATX_ATTR_VERITY
AttributeError: C attribute cannot be deleted
```

#### Expected behavior

`AttributeError` is not raised.

### Steps to reproduce

```
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade git+https://github.com/YoSTEALTH/Liburing
python3
>>> import liburing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dm/liburing-test/.venv/lib/python3.8/site-packages/liburing/__init__.py", line 17, in <module>
    del lib.STATX_ATTR_VERITY
AttributeError: C attribute cannot be deleted
```

Note: When I remove the two lines `del lib.STATX_ATTR_VERITY` and `del lib.STATX_ATTR_DAX` from `liburing/__init__.py` I can use the library just fine.

**Comment by YoSTEALTH** [comment]
Thanks @danielmitterdorfer for catching this bug, I have fixed this issue :)

**Comment by danielmitterdorfer** [comment]
That was fast. :) Thank you very much for the fix (and also the library!).

**Comment by danielmitterdorfer** [comment]
I've checked latest master (i.e. https://github.com/YoSTEALTH/Liburing/commit/822e60cbbbccd6b06a65154e128056fdf9ad6f98) in the same test environment and it works fine now. Thanks!
