### ISSUE TITLE
prep_socket doesn't work

### ISSUE THREAD

**Issue by ZisIsNotZis** [YoSTEALTH/Liburing#21]
Probably a really dumb question, but I just can get `io_uring_prep_socket` to work:
```python
from liburing import io_uring, io_uring_queue_init, io_uring_prep_socket, AF_INET, SOCK_STREAM, SOCK_NONBLOCK, IOSQE_ASYNC, io_uring_submit_and_wait, io_uring_peek_cqe, io_uring_get_sqe, io_uring_cqe, trap_error
ring = io_uring()
io_uring_queue_init(1024, ring)
sqe = io_uring_get_sqe(ring)
io_uring_prep_socket(sqe, AF_INET, SOCK_STREAM)
sqe.flags |= IOSQE_ASYNC
io_uring_submit_and_wait(ring, 1)
cqe = io_uring_cqe()
io_uring_peek_cqe(ring, cqe)
trap_error(cqe.res)
```
returns
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 10
      8 cqe = io_uring_cqe()
      9 io_uring_peek_cqe(ring, cqe)
---> 10 trap_error(cqe.res)

File src/liburing/error.pyx:1, in liburing.error.trap_error()

File src/liburing/error.pyx:34, in liburing.error.trap_error()

File src/liburing/error.pyx:40, in liburing.error.raise_error()

OSError: [Errno 22] Invalid argument
```

Any idea what's wrong? Kernel is 5.15.167.4-microsoft-standard-WSL2

**Comment by YoSTEALTH** [comment]
Could you try it without the `IOSQE_ASYNC`? Maybe the flag is not supported with the kernel you are using plus there was a bug with that flag as well, it is normally recommended not to use it.

Also should be using `io_uring_submit` and `io_uring_wait_cqe` as `io_uring_submit_and_wait` doesn't do what you think it does, naming of that C function is misleading.

If you haven't check out https://github.com/YoSTEALTH/Shakti it accounts for a lot of these weirdness and should be easy to use.

**Comment by ZisIsNotZis** [comment]
@YoSTEALTH Thanks for the response!
Actually that flag was added during debugging...
```python
from liburing import io_uring, io_uring_queue_init, io_uring_prep_socket, AF_INET, SOCK_STREAM, SOCK_NONBLOCK, IOSQE_ASYNC, io_uring_submit_and_wait, io_uring_peek_cqe, io_uring_get_sqe, io_uring_cqe, trap_error
ring = io_uring()
io_uring_queue_init(1024, ring)
sqe = io_uring_get_sqe(ring)
io_uring_prep_socket(sqe, AF_INET, SOCK_STREAM)
io_uring_submit(ring)
cqe = io_uring_cqe()
io_uring_wait_cqe(ring, cqe)
trap_error(cqe.res)
```
This still returns with the same error. Really wired. If I create socket using `socket.socket` and uring accept/listen on it works perfectly fine. Don't understand why.

The shakti library seems easier to use than this one! I'll definitely have a look at that

**Comment by YoSTEALTH** [comment]
Could be that `io_uring_prep_socket` does not support the kernel version you are using, maybe it was added in later version?

**Comment by ZisIsNotZis** [comment]
Ah yes, it is indeed the kernel. I upgraded to `6.6.36.6-microsoft-standard-WSL2+` and everything works now.
