### ISSUE TITLE
Request for examples

### ISSUE THREAD

**Issue by govardhangdg** [YoSTEALTH/Liburing#4]
As the `liburing` concepts are fairly new, it's difficult for beginners (like me) to do even the most basic of the tasks, like reading or reading. So, it is helpful if a couple simple examples on reading and writing can be added. 
Thanks.

**Comment by YoSTEALTH** [comment]
True, for now you can look at https://github.com/YoSTEALTH/Liburing/tree/master/test there are lots of features still being added and isn't even out yet, for example something like open and close comes in 5.6+

**Comment by govardhangdg** [comment]
Thanks. Will do.

**Comment by govardhangdg** [comment]
Hello, once again! As per your suggestions, I am referring to the test cases. I just wanted to make sure that what I've understood is right. `liburing.io_uring_peek_cqe` is used to check whether the files are ready for operations (read or write) and depending on the return value we can know if they are ready or not. `liburing.io_uring_wait_cqes` is a similar function but it blocks in case the files are not ready. Previously, in asynchronous IO (epoll and family), such things weren't supported, I guess.

But I fail to understand the role of `liburing.io_uring_cqe_seen` function. You've commented its use as "cleaning the old query". Can you please make this a bit more clear.

Thanks a lot.

**Comment by YoSTEALTH** [comment]
> Hello, once again! As per your suggestions, I am referring to the test cases. I just wanted to make sure that what I've understood is right. `liburing.io_uring_peek_cqe` is used to check whether the files are ready for operations (read or write) and depending on the return value we can know if they are ready or not. `liburing.io_uring_wait_cqes` is a similar function but it blocks in case the files are not ready. Previously, in asynchronous IO (epoll and family), such things weren't supported, I guess.
 
Yes, also I made it so only `>= 0` values are return, anything `< 0` will auto raise appropriate python exception.

> But I fail to understand the role of `liburing.io_uring_cqe_seen` function. You've commented its use as "cleaning the old query". Can you please make this a bit more clear?
 
If you have ready events like `cqes = [1, 2, 3]` `io_uring_cqe_seen(cqes[0])` will remove one event, now you are left with `cqes = [2, 3]`. Its like saying i have "handled" that ready event clear it.

> Also, can you please tell the meaning of `32` in `liburing.io_uring_queue_init(32, ring, 0)`? Does this refer to the maximum number of operations that can be stored on the ring at a time?
 
Max number of `sqe` you can use, i think its 32*2 internally (not sure why this is).

> And `1` in `liburing.io_uring_prep_writev(sqe, fd, vecs, 1, 0)`. Sometimes `len(vecs)` is used instead.

`1` = number of items you are supplying `iov = liburing.iovec(bytearray(5), bytearray(6))` # this would mean there are 2 items

> And `2` in `liburing.io_uring_wait_cqes(ring, cqes, 2)`

wait for `2` cqe to finish

> Thanks a lot.

I have updated the tests, there were few old codes in it.

**Comment by YoSTEALTH** [comment]
`io_uring_wait_cqes` is not really "blocking" like synchronous blocking. It has max timeout and other options, internally its still listening to events (poll, ...)

**Comment by govardhangdg** [comment]
> wait for 2 cqe to finish

Is this like `wait for atleast 2` (if there are more than 2 ready, then all of them are returned in `cqes`) OR `return exactly 2`. And of course, having a time limit can lead to empty or less returns.

> 1 = number of items you are supplying iov = liburing.iovec(bytearray(5), bytearray(6)) # this would mean there are 2 items

```python
two = bytearray(b'world')
vec_two = liburing.iovec(two)
liburing.io_uring_prep_writev(sqe, fd, vec_two, len(vec_two), 5)
```
Here, every letter of the word 'world' is considered a separate thing? i.e, a separate write?

**Comment by YoSTEALTH** [comment]
Don't quote me on it but I think its exactly `2` no more, no less.

"world" would be 1 write. The `len(vec_two)` would be `1`. `liburing.iovec` is a helper function i wrote to make things easy for python users, you can see details https://github.com/YoSTEALTH/Liburing/blob/master/liburing/helper.py#L55

> And liburing.io_uring_peek_cqe(ring, cqes), is this level triggered or edge-triggered (as in epoll), if it actually makes any sense in io_uring ?
I don't think `io_uring_peek_cqe` has anything to do with polling.

**Comment by YoSTEALTH** [comment]
`io_uring_peek_cqe` tells you how many events are ready. If you don't use `io_uring_cq_advance` or `io_uring_cqe_seen` afterwords and run `io_uring_peek_cqe` again it will tell you of the same ready event.

There is also `io_uring_peek_batch_cqe` which tells you about multiple events that are ready.

**Comment by govardhangdg** [comment]
> I don't think io_uring_peek_cqe has anything to do with polling.

No, I meant in the sense of actually giving information about readiness. The `epoll` syscall also has nothing to do with polling. It's just used to tell whether or not a file is ready for some operation (read or write or something else). 

> There is also io_uring_peek_batch_cqe which tells you about multiple events that are ready.

Thanks. This is what I was trying to achieve. It's good that it's already there.

Once again, thanks a lot. Really appreciate it!

**Comment by govardhangdg** [comment]
Is there something like `io_uring_cq_advance` or `io_uring_cqe_seen` for `io_uring_peek_batch_cqe`?

**Comment by YoSTEALTH** [comment]
Liburing can be hard to grasp, I took me a while to grasp it as well.

Maybe and example would explain clearly:
```
# single result
result = liburing.io_uring_peek_cqe(ring, cqes)
if result:
    cqe = cqes[0]

    # do something with cqe

    # I have seen the result, clearn it.
    liburing.io_uring_cqe_seen(ring, cqe)


# multiple results
results = liburing.io_uring_peek_batch_cqe(ring, cqes, 2)
if results:
    for i in range(results):
        cqe = cqes[i]

        # do something with cqe

    # I have seen all the results, clearn it.
    liburing.io_uring_cq_advance(ring, results)
