### ISSUE TITLE
incomplete requires list and kernel version check suggestion

### ISSUE THREAD

**Issue by openalmeida** [YoSTEALTH/Liburing#6]
Wow, [Simple File Example](https://github.com/YoSTEALTH/Liburing#simple-file-example) is awesome and friendly.

- requires list may add `python3-devel` (package name for Fedora, other Linux distros may different) or cause `build/temp.linux-x86_64-3.7/liburing._liburing.c:22:12: fatal error: pyconfig.h: No such file or directory`

- pip installing progress not check kernel version 5.5+ as condition or cause `build/temp.linux-x86_64-3.7/liburing._liburing.c:5664:12: error: ‘STATX_ATTR_VERITY’ undeclared (first use in this function)`

**Comment by YoSTEALTH** [comment]
I have added a Linux check https://github.com/YoSTEALTH/Liburing/commit/29863a2d03c95958bfbbaaf9094940feb549dd24 I hope this fixes/prevents these issues? I don't have a way to test for Fedora and others..., If you can, let me know if I need to further improve things.

Thanks

**Comment by openalmeida** [comment]
> I have added a Linux check [29863a2](https://github.com/YoSTEALTH/Liburing/commit/29863a2d03c95958bfbbaaf9094940feb549dd24) I hope this fixes/prevents these issues? I don't have a way to test for Fedora and others..., If you can, let me know if I need to further improve things.
> 
> Thanks

You are welcome, I'd prefer the one to say "thanks" is me, its you who let me have a chance to use io_uring features under Python.

Back to this issue itself, I think the 2nd error ("‘STATX_ATTR_VERITY’ undeclared " said above) make this liburing for python binding requires kernel 5.5+. Namely kernel 5.1+ is too old, because of [code about the "STATX_ATTR_VERITY"](https://github.com/YoSTEALTH/Liburing/blob/master/builder.py#L765)  is refer to kernel header , and it said "STATX_ATTR_VERITY (since Linux 5.5)" the https://man7.org/linux/man-pages/man2/statx.2.html.

Error about Python Development Header Files ("PDHF", e.g the python.h and pyconfig.h), I think it is required just because of common Python installing will not always provide its header files. But I only know it is named "python3-devel" under Fedora. 

Maybe some Python header specialized declare checking can detect PDHF is installed or not, namely we can checking but avoid the os package name based logic (sorry about my poor knowledge about cffi, otherwise I should submit a PR here).

**Comment by openalmeida** [comment]
I am happy I can help you for tests, especially installing test.

currenly `pip install --upgrade liburing` working well, but requires `python3-devel` and `kernel 5.5+` (I am formerly under kernel 5.3.16 before this issue submitted, and now updated to 5.7.9 for this repo)

**Comment by YoSTEALTH** [comment]
o right, nice catch, I will have `STATX_ATTR_VERITY` fixed up, this was something extra I added since Python didn't have `statx` support.

As for `python3-devel` I think you will need to install it as its specific to your distro and looks like its required.

Yes, you really do need to have linux 5.7 or 5.8 since there were major bug fixes in those.

**Comment by YoSTEALTH** [comment]
I have resolved `STATX_ATTR_VERITY` issue.
